export const Global = {
  MANUFACTURER: 'manufacturer',
  TAGS: 'tags',
  EMPTY_BASKET: 'The basket is empty!',
  MINUS_SIGN: '-',
  PLUS_SIGN: '+',
  ADD: 'Add',
  BRANDS: 'Brands',
  SORTING: 'Sorting',
  TAG: 'Tags',
  ALL: 'All',
  SEARCH_BRAND: 'Search Brand',
  SEARCH_TAG: 'Search Tag',
  LOGO_IMG_ALT: 'Locals market',
  RANDOM_IMG_URL: 'https://picsum.photos/300/300?random=',
};
