export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_REQUEST_SUCCES = 'GET_PRODUCT_REQUEST_SUCCES';
export const GET_PRODUCT_REQUEST_FAIL = 'GET_PRODUCT_REQUEST_FAIL';
export const GET_PRODUCT_REQUESTED= 'GET_PRODUCT_REQUESTED';
export const GET_TOTAL_PRODUCT_COUNT= 'GET_TOTAL_PRODUCT_COUNT';
export const GET_TOTAL_PRODUCT_COUNT_SUCCES= 'GET_TOTAL_PRODUCT_COUNT_SUCCES';
export const GET_TOTAL_PRODUCT_COUNT_FAIL= 'GET_TOTAL_PRODUCT_COUNT_FAIL';
export const GET_TOTAL_PRODUCT_COUNT_REQUESTED= 'GET_TOTAL_PRODUCT_COUNT_REQUESTED';
export const UPDATE_FILTER_OPTIONS = 'UPDATE_FILTER_OPTIONS'

