export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_REQUEST_SUCCES = 'GET_PRODUCT_REQUEST_SUCCES';
export const GET_PRODUCT_REQUEST_FAIL = 'GET_PRODUCT_REQUEST_FAIL';
export const GET_PRODUCT_REQUESTED= 'GET_PRODUCT_REQUESTED';

